# Generated by Django 6.0.4 on 2026-04-29 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Auto-generated. Unique per tenant.', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line_total values. Computed server-side.', max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Tax rate as a decimal (e.g. 0.16 = 16%).', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='subtotal × tax_rate. Computed server-side.', max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='subtotal + tax_amount. Computed server-side.', max_digits=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Immutable. Auto-assigned from the authenticated user.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'sales_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Auto-generated. Unique per tenant.', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Running total of payments received.', max_digits=14)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file.', null=True, upload_to='invoices/pdfs/%Y/%m/')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Immutable. Auto-assigned from the authenticated user.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.salesorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units. Must be > 0.')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Copied from Product.price at confirmation time. NEVER from frontend.', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_price. Computed server-side.', max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sales Order Line',
                'verbose_name_plural': 'Sales Order Lines',
                'db_table': 'sales_order_lines',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount. Must be > 0.', max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('payment_date', models.DateField(help_text='Date the payment was received.')),
                ('reference', models.CharField(blank=True, default='', help_text='External payment reference (transaction ID, check number, etc.).', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Immutable. Auto-assigned from the authenticated user.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'db_table': 'invoice_payments',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_payment_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_order_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sales_order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='sales_order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='unique_invoice_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_order_line_unit_price_non_negative'),
        ),
    ]
