# Generated by Django 6.0.4 on 2026-04-29 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name or business name of the customer.', max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email. Unique per tenant when provided.', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_id', models.CharField(blank=True, default='', help_text='Tax identification number (RFC, NIT, etc.). Unique per tenant when provided.', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('tenant', 'email'), name='unique_customer_email_per_tenant'), models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tenant', 'tax_id'), name='unique_customer_tax_id_per_tenant')],
            },
        ),
    ]
