# Generated by Django 6.0.4 on 2026-04-29 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Salida'), ('adjustment', 'Ajuste')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of units in this transaction (always positive).')),
                ('reference', models.CharField(blank=True, default='', help_text='External reference (e.g. purchase order, invoice number).', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
