# Generated by Django 6.0.4 on 2026-04-29 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Current stock level. Cannot be negative (DB constraint).')),
                ('last_movement_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent inventory movement.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Salida'), ('adjustment', 'Ajuste'), ('sale', 'Venta'), ('return', 'Devolución')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of units in this movement (always positive).')),
                ('quantity_before', models.IntegerField(help_text='Stock level BEFORE this movement was applied.')),
                ('quantity_after', models.IntegerField(help_text='Stock level AFTER this movement was applied.')),
                ('reference', models.CharField(blank=True, default='', help_text='External reference (e.g. PO number, invoice, sale order).', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Immutable. Auto-assigned from the authenticated user.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product'), name='unique_inventory_per_product'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_quantity_on_hand_non_negative'),
        ),
    ]
